### ISSUE TITLE
Publish javadoc for libraries to link to

### ISSUE THREAD

**Issue by alkemist** [reactive-streams/reactive-streams#101]
Libraries using the API should be able to link their Javadoc.

**Comment by rkuhn** [comment]
So, what exactly needs doing and how is it done? (i.e. I can of course manually push some HTML files, but this sounded like an opportunity for automatization)

**Comment by viktorklang** [comment]
I have fixed this, see: 

www.reactive-streams.org/reactive-streams-1.0.0.RC1-javadoc/
www.reactive-streams.org/reactive-streams-tck-1.0.0.RC1-javadoc/

**Comment by ben-manes** [comment]
fyi, javadoc.io offline linking seems to do the trick ([example](https://github.com/ben-manes/caffeine/commit/7c5115a7c303a9d07e05ea7ff69ecd9b06cd0d40#diff-e907e60e04da719cc3c533ffe49ff6f5))

**Comment by viktorklang** [comment]
This seems to work?

https://www.javadoc.io/doc/org.reactivestreams/reactive-streams/1.0.0

**Comment by ben-manes** [comment]
That's the link you might use for users, e.g. on a badge. The issue you faced was because the directory layout isn't public (404s) and the JavaDoc tool can't find the `package-list`. If instead you link offline with the reference URL, the output will be correct. That means you don't need to host your own JavaDoc and can link yours to others who don't host theirs either.

**Comment by viktorklang** [comment]
Ah, OK, thanks for the update!

Hosting the javadoc on the site is really not a problem, especially given how much data it is :)

**Comment by ben-manes** [comment]
yep, this was more of a friendly fyi for future projects and not an ask =)

**Comment by viktorklang** [comment]
@ben-manes Thanks! :)
